#!/usr/bin/env bash
# Concatenates every app's SQL, in dependency order, into supabase/restore_all.sql.
# Lexica, Oratio and Cortex Core API share ONE Supabase project (public.profiles
# is shared), so the order matters: Oratio's schema creates profiles first.
set -euo pipefail
cd "$(dirname "$0")/.."

FILES=(
  apps/oratio/supabase/schema.sql
  apps/oratio/supabase/migration_add_qa_feature.sql
  apps/oratio/supabase/migration_add_swap_request.sql
  apps/oratio/supabase/migration_replica_identity.sql
  apps/oratio/supabase/fix_rating_constraint.sql
  apps/oratio/supabase/migration_queue_heartbeat.sql
  apps/oratio/supabase/seed_questions_v2.sql
  apps/lexica/supabase/migration_study_buddy.sql
  apps/lexica/supabase/migration_study_buddy_fix.sql
  apps/lexica/supabase/migration_study_buddy_fix2.sql
  apps/lexica/supabase/migration_study_buddy_fix3.sql
  apps/lexica/supabase/migration_study_buddy_fix4.sql
  apps/lexica/supabase/migration_game_challenges.sql
  apps/lexica/supabase/migration_add_response.sql
  apps/cortex-core-api/supabase/migration_phase1_core.sql
  apps/cortex-core-api/supabase/migration_studio.sql
  apps/cortex-core-api/supabase/seed_studio_lexemes.sql
)

OUT=supabase/restore_all.sql
{
  echo "-- GENERATED by supabase/build-restore.sh — do not edit by hand."
  echo "-- Rebuilds the shared Supabase schema for Oratio, Lexica and Cortex Core API"
  echo "-- plus the IELTS question seed. Safe to re-run. Contains no user data."
  echo
  echo 'create extension if not exists "uuid-ossp";'
  for f in "${FILES[@]}"; do
    printf '\n-- ============================================================\n'
    printf -- '-- %s\n' "$f"
    printf -- '-- ============================================================\n\n'
    cat "$f"
    echo
  done
} > "$OUT"
echo "Wrote $OUT"
