-- GENERATED by supabase/build-restore.sh — do not edit by hand.
-- Rebuilds the shared Supabase schema for Oratio, Lexica and Cortex Core API
-- plus the IELTS question seed. Safe to re-run. Contains no user data.

create extension if not exists "uuid-ossp";

-- ============================================================
-- apps/oratio/supabase/schema.sql
-- ============================================================

-- ============================================
-- SpeakMate Database Schema
-- Run this in Supabase SQL Editor
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- ENUMS
-- ============================================

-- Match queue status enum
DO $$ BEGIN
    CREATE TYPE match_queue_status AS ENUM ('waiting', 'matched', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Match status enum
DO $$ BEGIN
    CREATE TYPE match_status AS ENUM ('pending', 'active', 'finished', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- TABLES
-- ============================================

-- Profiles table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    email TEXT,
    target_band DECIMAL(2,1) DEFAULT 7.0 CHECK (target_band >= 1 AND target_band <= 9),
    current_band DECIMAL(2,1) DEFAULT 5.5 CHECK (current_band >= 1 AND current_band <= 9),
    avatar_url TEXT,
    native_language TEXT,
    country TEXT,
    total_sessions INTEGER DEFAULT 0,
    total_minutes INTEGER DEFAULT 0,
    current_streak INTEGER DEFAULT 0,
    longest_streak INTEGER DEFAULT 0,
    last_practice_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Match queue table
CREATE TABLE IF NOT EXISTS public.match_queue (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    target_band_min DECIMAL(2,1) DEFAULT 5.0 CHECK (target_band_min >= 1 AND target_band_min <= 9),
    target_band_max DECIMAL(2,1) DEFAULT 7.5 CHECK (target_band_max >= 1 AND target_band_max <= 9),
    status match_queue_status DEFAULT 'waiting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ DEFAULT NOW(), -- heartbeat, updated on every poll
    UNIQUE(user_id) -- User can only be in queue once
);

-- IELTS questions table for Q&A practice
CREATE TABLE IF NOT EXISTS public.ielts_questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    part INTEGER NOT NULL CHECK (part >= 1 AND part <= 3),
    category TEXT NOT NULL,
    question_text TEXT NOT NULL,
    difficulty TEXT DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Matches table
CREATE TABLE IF NOT EXISTS public.matches (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user1_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user2_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    interviewer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    candidate_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    room_id TEXT NOT NULL UNIQUE,
    status match_status DEFAULT 'pending',
    topic TEXT,
    current_question_id UUID REFERENCES public.ielts_questions(id),
    questions_asked UUID[] DEFAULT '{}',
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CHECK (user1_id != user2_id), -- Users can't match with themselves
    CHECK (interviewer_id IN (user1_id, user2_id) OR interviewer_id IS NULL),
    CHECK (candidate_id IN (user1_id, user2_id) OR candidate_id IS NULL)
);

-- Session feedback table
CREATE TABLE IF NOT EXISTS public.session_feedback (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    match_id UUID NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    from_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    to_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    overall_rating INTEGER NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 9),
    would_match_again BOOLEAN,
    feedback_tags TEXT[] DEFAULT '{}',
    comments TEXT,
    scores JSONB, -- { fluency: 6.5, vocabulary: 6.0, grammar: 5.5, pronunciation: 6.5, overall: 6.1 }
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(match_id, from_user_id) -- One feedback per user per match
);

-- ============================================
-- INDEXES
-- ============================================

-- IELTS questions indexes
CREATE INDEX IF NOT EXISTS idx_ielts_questions_part ON public.ielts_questions(part);
CREATE INDEX IF NOT EXISTS idx_ielts_questions_category ON public.ielts_questions(category);
CREATE INDEX IF NOT EXISTS idx_ielts_questions_difficulty ON public.ielts_questions(difficulty);

-- Match queue indexes for faster matching queries
CREATE INDEX IF NOT EXISTS idx_match_queue_status ON public.match_queue(status);
CREATE INDEX IF NOT EXISTS idx_match_queue_waiting ON public.match_queue(status, created_at) WHERE status = 'waiting';
CREATE INDEX IF NOT EXISTS idx_match_queue_user ON public.match_queue(user_id);
CREATE INDEX IF NOT EXISTS idx_match_queue_waiting_seen ON public.match_queue(status, last_seen_at) WHERE status = 'waiting';

-- Matches indexes
CREATE INDEX IF NOT EXISTS idx_matches_user1 ON public.matches(user1_id);
CREATE INDEX IF NOT EXISTS idx_matches_user2 ON public.matches(user2_id);
CREATE INDEX IF NOT EXISTS idx_matches_status ON public.matches(status);
CREATE INDEX IF NOT EXISTS idx_matches_room ON public.matches(room_id);

-- Session feedback indexes
CREATE INDEX IF NOT EXISTS idx_feedback_match ON public.session_feedback(match_id);
CREATE INDEX IF NOT EXISTS idx_feedback_from_user ON public.session_feedback(from_user_id);
CREATE INDEX IF NOT EXISTS idx_feedback_to_user ON public.session_feedback(to_user_id);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ielts_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_feedback ENABLE ROW LEVEL SECURITY;

-- IELTS questions policies (read-only for all authenticated users)
DROP POLICY IF EXISTS "IELTS questions are viewable by authenticated users" ON public.ielts_questions;
CREATE POLICY "IELTS questions are viewable by authenticated users"
    ON public.ielts_questions FOR SELECT
    USING (auth.role() = 'authenticated');

-- Profiles policies
DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Profiles are viewable by everyone"
    ON public.profiles FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- Match queue policies
DROP POLICY IF EXISTS "Users can view their own queue entry" ON public.match_queue;
CREATE POLICY "Users can view their own queue entry"
    ON public.match_queue FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert themselves into queue" ON public.match_queue;
CREATE POLICY "Users can insert themselves into queue"
    ON public.match_queue FOR INSERT
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own queue entry" ON public.match_queue;
CREATE POLICY "Users can update their own queue entry"
    ON public.match_queue FOR UPDATE
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own queue entry" ON public.match_queue;
CREATE POLICY "Users can delete their own queue entry"
    ON public.match_queue FOR DELETE
    USING (auth.uid() = user_id);

-- Matches policies
DROP POLICY IF EXISTS "Users can view matches they are part of" ON public.matches;
CREATE POLICY "Users can view matches they are part of"
    ON public.matches FOR SELECT
    USING (auth.uid() = user1_id OR auth.uid() = user2_id);

DROP POLICY IF EXISTS "Users can update matches they are part of" ON public.matches;
CREATE POLICY "Users can update matches they are part of"
    ON public.matches FOR UPDATE
    USING (auth.uid() = user1_id OR auth.uid() = user2_id);

-- Note: INSERT for matches should be done via service role (server-side)
-- This prevents race conditions in matchmaking

-- Session feedback policies
DROP POLICY IF EXISTS "Users can view feedback they gave or received" ON public.session_feedback;
CREATE POLICY "Users can view feedback they gave or received"
    ON public.session_feedback FOR SELECT
    USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

DROP POLICY IF EXISTS "Users can insert feedback for matches they participated in" ON public.session_feedback;
CREATE POLICY "Users can insert feedback for matches they participated in"
    ON public.session_feedback FOR INSERT
    WITH CHECK (
        auth.uid() = from_user_id 
        AND EXISTS (
            SELECT 1 FROM public.matches 
            WHERE id = match_id 
            AND (user1_id = auth.uid() OR user2_id = auth.uid())
        )
    );

DROP POLICY IF EXISTS "Users can update their own feedback" ON public.session_feedback;
CREATE POLICY "Users can update their own feedback"
    ON public.session_feedback FOR UPDATE
    USING (auth.uid() = from_user_id);

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Function to auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, email)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
        NEW.email
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call function on new user signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for profiles
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================
-- REALTIME
-- ============================================

-- Add tables to the publication to enable realtime subscriptions
-- This is crucial for the matchmaking to work!
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'matches') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.matches;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'match_queue') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.match_queue;
  END IF;
END $$;


-- Function to update user stats after a match ends
CREATE OR REPLACE FUNCTION public.update_user_stats_after_match()
RETURNS TRIGGER AS $$
DECLARE
    match_duration INTEGER;
BEGIN
    -- Only run when match status changes to 'finished'
    IF NEW.status = 'finished' AND OLD.status != 'finished' THEN
        -- Calculate duration in minutes
        match_duration := EXTRACT(EPOCH FROM (NEW.ended_at - NEW.started_at)) / 60;
        
        -- Update user1 stats
        UPDATE public.profiles
        SET 
            total_sessions = total_sessions + 1,
            total_minutes = total_minutes + match_duration,
            last_practice_date = CURRENT_DATE,
            current_streak = CASE 
                WHEN last_practice_date = CURRENT_DATE - INTERVAL '1 day' THEN current_streak + 1
                WHEN last_practice_date = CURRENT_DATE THEN current_streak
                ELSE 1
            END,
            longest_streak = GREATEST(longest_streak, 
                CASE 
                    WHEN last_practice_date = CURRENT_DATE - INTERVAL '1 day' THEN current_streak + 1
                    WHEN last_practice_date = CURRENT_DATE THEN current_streak
                    ELSE 1
                END
            )
        WHERE id = NEW.user1_id;
        
        -- Update user2 stats
        UPDATE public.profiles
        SET 
            total_sessions = total_sessions + 1,
            total_minutes = total_minutes + match_duration,
            last_practice_date = CURRENT_DATE,
            current_streak = CASE 
                WHEN last_practice_date = CURRENT_DATE - INTERVAL '1 day' THEN current_streak + 1
                WHEN last_practice_date = CURRENT_DATE THEN current_streak
                ELSE 1
            END,
            longest_streak = GREATEST(longest_streak, 
                CASE 
                    WHEN last_practice_date = CURRENT_DATE - INTERVAL '1 day' THEN current_streak + 1
                    WHEN last_practice_date = CURRENT_DATE THEN current_streak
                    ELSE 1
                END
            )
        WHERE id = NEW.user2_id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to update stats when match ends
DROP TRIGGER IF EXISTS on_match_finished ON public.matches;
CREATE TRIGGER on_match_finished
    AFTER UPDATE ON public.matches
    FOR EACH ROW EXECUTE FUNCTION public.update_user_stats_after_match();

-- Function to update current_band from peer feedback
CREATE OR REPLACE FUNCTION public.update_current_band_from_feedback()
RETURNS TRIGGER AS $$
BEGIN
    -- Only update if feedback has scores
    IF NEW.scores IS NOT NULL AND (NEW.scores->>'overall') IS NOT NULL THEN
        -- Update the recipient's current_band with weighted average of recent feedback
        -- Prioritize recent 30 days, with minimum 3 feedback sessions for stability
        UPDATE public.profiles
        SET current_band = (
            SELECT CASE 
                WHEN COUNT(*) >= 3 THEN 
                    ROUND(AVG((scores->>'overall')::decimal), 1)
                ELSE 
                    current_band  -- Keep current if not enough data
            END
            FROM session_feedback
            WHERE to_user_id = NEW.to_user_id
                AND scores IS NOT NULL
                AND (scores->>'overall') IS NOT NULL
                AND created_at >= NOW() - INTERVAL '30 days'
        )
        WHERE id = NEW.to_user_id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to update band after receiving feedback
DROP TRIGGER IF EXISTS on_feedback_received ON public.session_feedback;
CREATE TRIGGER on_feedback_received
    AFTER INSERT ON public.session_feedback
    FOR EACH ROW EXECUTE FUNCTION public.update_current_band_from_feedback();

-- ============================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================

-- Uncomment to add sample data for testing
/*
INSERT INTO public.profiles (id, username, email, target_band, current_band, country, native_language)
VALUES 
    ('00000000-0000-0000-0000-000000000001', 'test_user_1', 'test1@example.com', 7.0, 6.0, 'Vietnam', 'Vietnamese'),
    ('00000000-0000-0000-0000-000000000002', 'test_user_2', 'test2@example.com', 7.5, 6.5, 'China', 'Chinese');
*/



-- ============================================================
-- apps/oratio/supabase/migration_add_qa_feature.sql
-- ============================================================

-- ============================================
-- Migration: Add Q&A Feature to Existing Database
-- Safe to run on existing database
-- Date: 2026-03-21
-- ============================================

-- 1. Create ielts_questions table (only if not exists)
CREATE TABLE IF NOT EXISTS public.ielts_questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    part INTEGER NOT NULL CHECK (part >= 1 AND part <= 3),
    category TEXT NOT NULL,
    question_text TEXT NOT NULL,
    difficulty TEXT DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add new columns to matches table (safe with DO blocks)
DO $$ 
BEGIN
    -- Add interviewer_id column if not exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'matches' 
        AND column_name = 'interviewer_id'
    ) THEN
        ALTER TABLE public.matches 
        ADD COLUMN interviewer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
    END IF;

    -- Add candidate_id column if not exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'matches' 
        AND column_name = 'candidate_id'
    ) THEN
        ALTER TABLE public.matches 
        ADD COLUMN candidate_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
    END IF;

    -- Add current_question_id column if not exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'matches' 
        AND column_name = 'current_question_id'
    ) THEN
        ALTER TABLE public.matches 
        ADD COLUMN current_question_id UUID REFERENCES public.ielts_questions(id);
    END IF;

    -- Add questions_asked column if not exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'matches' 
        AND column_name = 'questions_asked'
    ) THEN
        ALTER TABLE public.matches 
        ADD COLUMN questions_asked UUID[] DEFAULT '{}';
    END IF;
END $$;

-- 3. Add constraints to matches table (safe with IF NOT EXISTS)
DO $$
BEGIN
    -- Check constraint for interviewer_id
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'matches_interviewer_valid'
    ) THEN
        ALTER TABLE public.matches 
        ADD CONSTRAINT matches_interviewer_valid 
        CHECK (interviewer_id IN (user1_id, user2_id) OR interviewer_id IS NULL);
    END IF;

    -- Check constraint for candidate_id
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'matches_candidate_valid'
    ) THEN
        ALTER TABLE public.matches 
        ADD CONSTRAINT matches_candidate_valid 
        CHECK (candidate_id IN (user1_id, user2_id) OR candidate_id IS NULL);
    END IF;
END $$;

-- 4. Create indexes (safe with IF NOT EXISTS)
CREATE INDEX IF NOT EXISTS idx_ielts_questions_part ON public.ielts_questions(part);
CREATE INDEX IF NOT EXISTS idx_ielts_questions_category ON public.ielts_questions(category);
CREATE INDEX IF NOT EXISTS idx_ielts_questions_difficulty ON public.ielts_questions(difficulty);

-- 5. Enable RLS on ielts_questions
ALTER TABLE public.ielts_questions ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS policy for ielts_questions (drop first if exists)
DROP POLICY IF EXISTS "IELTS questions are viewable by authenticated users" ON public.ielts_questions;
CREATE POLICY "IELTS questions are viewable by authenticated users"
    ON public.ielts_questions FOR SELECT
    USING (auth.role() = 'authenticated');

-- 7. Add ielts_questions to realtime publication (if not already added)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND tablename = 'ielts_questions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.ielts_questions;
  END IF;
END $$;

-- ============================================
-- Verification Queries (optional - comment out before running)
-- ============================================

-- Uncomment to verify after migration:
/*
-- Check new columns in matches table
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'matches' 
AND column_name IN ('interviewer_id', 'candidate_id', 'current_question_id', 'questions_asked');

-- Check ielts_questions table exists
SELECT COUNT(*) as question_count FROM public.ielts_questions;

-- Check indexes
SELECT indexname FROM pg_indexes 
WHERE tablename = 'ielts_questions';
*/

-- ============================================
-- Success Message
-- ============================================

DO $$
BEGIN
    RAISE NOTICE '✅ Migration completed successfully!';
    RAISE NOTICE '📝 Next step: Run seed_questions.sql to populate IELTS questions';
END $$;


-- ============================================================
-- apps/oratio/supabase/migration_add_swap_request.sql
-- ============================================================

-- Migration: Add swap_requested_by column to matches table
-- This enables the swap consent mechanism where one user requests
-- and the other must accept/decline the role swap.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'matches'
        AND column_name = 'swap_requested_by'
    ) THEN
        ALTER TABLE public.matches
            ADD COLUMN swap_requested_by UUID REFERENCES auth.users(id) DEFAULT NULL;
        RAISE NOTICE 'Column swap_requested_by added to matches';
    ELSE
        RAISE NOTICE 'Column swap_requested_by already exists';
    END IF;
END $$;

-- Verify
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'matches'
AND column_name = 'swap_requested_by';


-- ============================================================
-- apps/oratio/supabase/migration_replica_identity.sql
-- ============================================================

-- Enable REPLICA IDENTITY FULL on matches table
-- Required for Supabase Realtime to properly deliver UPDATE events through RLS
ALTER TABLE public.matches REPLICA IDENTITY FULL;


-- ============================================================
-- apps/oratio/supabase/fix_rating_constraint.sql
-- ============================================================

-- Fix overall_rating constraint from 1-5 to 1-9 for IELTS band scores
-- Drop the old constraint
ALTER TABLE public.session_feedback 
DROP CONSTRAINT IF EXISTS session_feedback_overall_rating_check;

-- Add new constraint with correct range (1-9)
ALTER TABLE public.session_feedback 
ADD CONSTRAINT session_feedback_overall_rating_check 
CHECK (overall_rating >= 1 AND overall_rating <= 9);


-- ============================================================
-- apps/oratio/supabase/migration_queue_heartbeat.sql
-- ============================================================

-- Matchmaking heartbeat.
-- findMatch() now updates last_seen_at on every poll and only matches users
-- seen in the last 15s. created_at stays fixed so FIFO order is kept.
-- Run this BEFORE deploying the matching app code.

ALTER TABLE public.match_queue
  ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.match_queue
  SET last_seen_at = created_at
  WHERE last_seen_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_match_queue_waiting_seen
  ON public.match_queue(status, last_seen_at) WHERE status = 'waiting';


-- ============================================================
-- apps/oratio/supabase/seed_questions_v2.sql
-- ============================================================

-- ============================================
-- IELTS Questions Seed Data v2 (Expanded)
-- Run this after running schema.sql
-- Replaces the original seed_questions.sql
-- Total: ~300 questions across Part 1, Part 2, Part 3
-- ============================================

-- Clear foreign key references before deleting questions
UPDATE public.matches SET current_question_id = NULL, questions_asked = '{}';
DELETE FROM public.ielts_questions;

-- ============================================
-- PART 1: Introduction and Interview (4-5 minutes)
-- Familiar topics, short answers expected
-- ~120 questions across 20 categories
-- ============================================

INSERT INTO public.ielts_questions (part, category, question_text, difficulty) VALUES

-- Home & Accommodation (6)
(1, 'Home & Accommodation', 'Do you live in a house or an apartment?', 'easy'),
(1, 'Home & Accommodation', 'Can you describe the place where you live?', 'easy'),
(1, 'Home & Accommodation', 'What do you like most about living there?', 'medium'),
(1, 'Home & Accommodation', 'What changes would you like to make to your home?', 'medium'),
(1, 'Home & Accommodation', 'Do you plan to live there for a long time?', 'easy'),
(1, 'Home & Accommodation', 'Is the area where you live good for families?', 'medium'),

-- Hometown (6)
(1, 'Hometown', 'Where are you from?', 'easy'),
(1, 'Hometown', 'What do you like about your hometown?', 'easy'),
(1, 'Hometown', 'Has your hometown changed much since you were a child?', 'medium'),
(1, 'Hometown', 'Would you like to live there in the future?', 'medium'),
(1, 'Hometown', 'What is your hometown famous for?', 'medium'),
(1, 'Hometown', 'What kind of jobs do people do in your hometown?', 'medium'),

-- Work & Studies (8)
(1, 'Work & Studies', 'Do you work or are you a student?', 'easy'),
(1, 'Work & Studies', 'What subject are you studying?', 'easy'),
(1, 'Work & Studies', 'Why did you choose this subject?', 'medium'),
(1, 'Work & Studies', 'What do you find most interesting about your studies?', 'medium'),
(1, 'Work & Studies', 'What do you do for work?', 'easy'),
(1, 'Work & Studies', 'Why did you choose this job?', 'medium'),
(1, 'Work & Studies', 'What do you like most about your job?', 'medium'),
(1, 'Work & Studies', 'Do you prefer to study alone or in a group?', 'medium'),

-- Hobbies & Free Time (6)
(1, 'Hobbies & Free Time', 'What do you like to do in your free time?', 'easy'),
(1, 'Hobbies & Free Time', 'Do you have any hobbies?', 'easy'),
(1, 'Hobbies & Free Time', 'How much time do you spend on your hobbies?', 'medium'),
(1, 'Hobbies & Free Time', 'Have your hobbies changed since you were a child?', 'medium'),
(1, 'Hobbies & Free Time', 'Do you prefer spending time alone or with friends?', 'medium'),
(1, 'Hobbies & Free Time', 'What new hobby would you like to try?', 'medium'),

-- Music (6)
(1, 'Music', 'Do you like listening to music?', 'easy'),
(1, 'Music', 'What kind of music do you like?', 'easy'),
(1, 'Music', 'Have you ever been to a concert?', 'medium'),
(1, 'Music', 'Do you play any musical instruments?', 'easy'),
(1, 'Music', 'Has your taste in music changed over time?', 'medium'),
(1, 'Music', 'Do you think music can affect people''s mood?', 'medium'),

-- Technology (6)
(1, 'Technology', 'Do you use computers or smartphones often?', 'easy'),
(1, 'Technology', 'What do you mainly use technology for?', 'medium'),
(1, 'Technology', 'How has technology changed your life?', 'medium'),
(1, 'Technology', 'Do you think people rely too much on technology?', 'hard'),
(1, 'Technology', 'What was the last app you downloaded?', 'easy'),
(1, 'Technology', 'How do you feel about social media?', 'medium'),

-- Food & Cooking (6)
(1, 'Food & Cooking', 'What kind of food do you like?', 'easy'),
(1, 'Food & Cooking', 'Do you enjoy cooking?', 'easy'),
(1, 'Food & Cooking', 'What is a typical meal in your country?', 'medium'),
(1, 'Food & Cooking', 'Have your eating habits changed over the years?', 'medium'),
(1, 'Food & Cooking', 'Do you prefer eating at home or in restaurants?', 'medium'),
(1, 'Food & Cooking', 'Is there any food you dislike?', 'easy'),

-- Travel (6)
(1, 'Travel', 'Do you like travelling?', 'easy'),
(1, 'Travel', 'Have you travelled to many places?', 'easy'),
(1, 'Travel', 'What was your most memorable trip?', 'medium'),
(1, 'Travel', 'Do you prefer travelling alone or with others?', 'medium'),
(1, 'Travel', 'Where would you like to travel in the future?', 'medium'),
(1, 'Travel', 'Do you prefer to travel by plane or by train?', 'easy'),

-- Weather & Seasons (6)
(1, 'Weather & Seasons', 'What is the weather like in your country?', 'easy'),
(1, 'Weather & Seasons', 'What is your favourite season?', 'easy'),
(1, 'Weather & Seasons', 'Does the weather affect how you feel?', 'medium'),
(1, 'Weather & Seasons', 'What do you usually do on rainy days?', 'easy'),
(1, 'Weather & Seasons', 'Would you prefer to live somewhere with a warm or cold climate?', 'medium'),
(1, 'Weather & Seasons', 'Has the weather in your area changed in recent years?', 'medium'),

-- Shopping (6)
(1, 'Shopping', 'Do you enjoy shopping?', 'easy'),
(1, 'Shopping', 'What do you like to buy?', 'easy'),
(1, 'Shopping', 'Do you prefer shopping online or in stores?', 'medium'),
(1, 'Shopping', 'What was the last thing you bought?', 'easy'),
(1, 'Shopping', 'Do you ever buy things you don''t need?', 'medium'),
(1, 'Shopping', 'Are there many shops near where you live?', 'easy'),

-- Sports & Exercise (6)
(1, 'Sports & Exercise', 'Do you play any sports?', 'easy'),
(1, 'Sports & Exercise', 'What kind of exercise do you do?', 'easy'),
(1, 'Sports & Exercise', 'How often do you exercise?', 'easy'),
(1, 'Sports & Exercise', 'Did you play sports when you were a child?', 'medium'),
(1, 'Sports & Exercise', 'Do you prefer playing sports or watching them?', 'medium'),
(1, 'Sports & Exercise', 'Is sport popular in your country?', 'medium'),

-- Reading (6)
(1, 'Reading', 'Do you enjoy reading?', 'easy'),
(1, 'Reading', 'What kind of books do you like?', 'easy'),
(1, 'Reading', 'Do you prefer reading paper books or e-books?', 'medium'),
(1, 'Reading', 'How often do you read?', 'easy'),
(1, 'Reading', 'Did you read much as a child?', 'medium'),
(1, 'Reading', 'Is there a book that had a big impact on you?', 'medium'),

-- Movies & TV (6)
(1, 'Movies & TV', 'Do you like watching movies?', 'easy'),
(1, 'Movies & TV', 'What kind of movies do you enjoy?', 'easy'),
(1, 'Movies & TV', 'Do you prefer to watch movies at home or at the cinema?', 'medium'),
(1, 'Movies & TV', 'How often do you watch TV?', 'easy'),
(1, 'Movies & TV', 'Who is your favourite actor or actress?', 'easy'),
(1, 'Movies & TV', 'Do you think TV is a good way to learn a language?', 'medium'),

-- Friends & Social Life (6)
(1, 'Friends & Social Life', 'How do you usually spend time with your friends?', 'easy'),
(1, 'Friends & Social Life', 'How often do you see your friends?', 'easy'),
(1, 'Friends & Social Life', 'Do you prefer having a few close friends or many friends?', 'medium'),
(1, 'Friends & Social Life', 'Have you made any new friends recently?', 'medium'),
(1, 'Friends & Social Life', 'Is it easy to make friends in your city?', 'medium'),
(1, 'Friends & Social Life', 'What qualities do you look for in a friend?', 'medium'),

-- Daily Routine (6)
(1, 'Daily Routine', 'What do you usually do in the mornings?', 'easy'),
(1, 'Daily Routine', 'Do you have a fixed daily routine?', 'easy'),
(1, 'Daily Routine', 'What time do you usually go to bed?', 'easy'),
(1, 'Daily Routine', 'Has your daily routine changed recently?', 'medium'),
(1, 'Daily Routine', 'What is your favourite part of the day?', 'medium'),
(1, 'Daily Routine', 'Do you think having a routine is important?', 'medium'),

-- Transport (6)
(1, 'Transport', 'How do you usually get to work or school?', 'easy'),
(1, 'Transport', 'What is the public transport like in your area?', 'medium'),
(1, 'Transport', 'Do you prefer driving or taking public transport?', 'medium'),
(1, 'Transport', 'Have you ever had a long journey?', 'medium'),
(1, 'Transport', 'Would you like to have a car?', 'easy'),
(1, 'Transport', 'How could the transport in your area be improved?', 'medium'),

-- Languages (6)
(1, 'Languages', 'What languages do you speak?', 'easy'),
(1, 'Languages', 'How long have you been learning English?', 'easy'),
(1, 'Languages', 'Do you think it is important to learn other languages?', 'medium'),
(1, 'Languages', 'What do you find most difficult about learning English?', 'medium'),
(1, 'Languages', 'Would you like to learn any other languages?', 'medium'),
(1, 'Languages', 'How do you usually practise English?', 'easy'),

-- Animals & Pets (6)
(1, 'Animals & Pets', 'Do you have any pets?', 'easy'),
(1, 'Animals & Pets', 'What is your favourite animal?', 'easy'),
(1, 'Animals & Pets', 'Did you have any pets when you were a child?', 'easy'),
(1, 'Animals & Pets', 'Are there many animals in your area?', 'medium'),
(1, 'Animals & Pets', 'Do you think it is important to protect wild animals?', 'medium'),
(1, 'Animals & Pets', 'Would you like to have an unusual pet?', 'medium'),

-- Festivals & Celebrations (6)
(1, 'Festivals & Celebrations', 'What is the most important festival in your country?', 'easy'),
(1, 'Festivals & Celebrations', 'How do people celebrate birthdays in your country?', 'easy'),
(1, 'Festivals & Celebrations', 'Do you enjoy going to parties?', 'easy'),
(1, 'Festivals & Celebrations', 'What was the last celebration you attended?', 'medium'),
(1, 'Festivals & Celebrations', 'Do you think traditional celebrations are important?', 'medium'),
(1, 'Festivals & Celebrations', 'How have festivals changed compared to the past?', 'medium'),

-- Nature & Outdoors (6)
(1, 'Nature & Outdoors', 'Do you spend much time outdoors?', 'easy'),
(1, 'Nature & Outdoors', 'What outdoor activities do you enjoy?', 'easy'),
(1, 'Nature & Outdoors', 'Is there much green space near where you live?', 'medium'),
(1, 'Nature & Outdoors', 'Do you prefer the countryside or the city?', 'medium'),
(1, 'Nature & Outdoors', 'When was the last time you visited a park or garden?', 'easy'),
(1, 'Nature & Outdoors', 'Do you think people today spend enough time in nature?', 'medium');


-- ============================================
-- PART 2: Individual Long Turn (3-4 minutes)
-- Candidate speaks for 1-2 minutes on a topic card
-- ~60 questions across 10 categories
-- ============================================

INSERT INTO public.ielts_questions (part, category, question_text, difficulty) VALUES

-- Person (8)
(2, 'Person', 'Describe a person you admire. You should say: who this person is, how you know them, what qualities they have, and explain why you admire them.', 'medium'),
(2, 'Person', 'Describe a family member you are close to. You should say: who this person is, what they are like, what you do together, and explain why you are close.', 'medium'),
(2, 'Person', 'Describe someone who has had an important influence on your life. You should say: who they are, how you met them, what influence they have had, and explain why this person is important to you.', 'hard'),
(2, 'Person', 'Describe a friend you have known for a long time. You should say: who they are, how you met, what you enjoy doing together, and explain why this friendship has lasted.', 'medium'),
(2, 'Person', 'Describe a teacher who has influenced you. You should say: who the teacher was, what subject they taught, what was special about them, and explain how they influenced you.', 'medium'),
(2, 'Person', 'Describe someone you would like to meet. You should say: who this person is, why you want to meet them, what you would say to them, and explain why meeting them would be special.', 'hard'),
(2, 'Person', 'Describe someone who is good at their job. You should say: who this person is, what job they do, how you know them, and explain why they are good at their job.', 'medium'),
(2, 'Person', 'Describe an elderly person you respect. You should say: who this person is, how you know them, what they have done, and explain why you respect them.', 'medium'),

-- Place (8)
(2, 'Place', 'Describe a place you like to visit. You should say: where it is, how often you go there, what you do there, and explain why you like this place.', 'medium'),
(2, 'Place', 'Describe a city you have visited and enjoyed. You should say: where it is, when you went there, what you did there, and explain why you enjoyed it.', 'medium'),
(2, 'Place', 'Describe a building or monument that you find impressive. You should say: what it is, where it is located, what it looks like, and explain why you find it impressive.', 'hard'),
(2, 'Place', 'Describe a quiet place you like to go to. You should say: where this place is, how you found it, how often you go there, and explain why you like it.', 'medium'),
(2, 'Place', 'Describe a place where you feel relaxed. You should say: where it is, what it looks like, what you do there, and explain why you feel relaxed there.', 'medium'),
(2, 'Place', 'Describe a foreign country you would like to visit. You should say: which country it is, what you know about it, what you would do there, and explain why you want to visit it.', 'medium'),
(2, 'Place', 'Describe a place that has been important in your childhood. You should say: where it is, when you used to go there, what you did there, and explain why it was important.', 'medium'),
(2, 'Place', 'Describe a restaurant or café you enjoy. You should say: where it is, what it looks like, what you eat or drink there, and explain why you enjoy going there.', 'easy'),

-- Object (6)
(2, 'Object', 'Describe something you own that is very important to you. You should say: what it is, how long you have had it, why it is important to you, and explain what you would do if you lost it.', 'medium'),
(2, 'Object', 'Describe a book that you have read and enjoyed. You should say: what the book is about, when you read it, why you chose it, and explain why you enjoyed it.', 'medium'),
(2, 'Object', 'Describe a gift you gave to someone. You should say: what the gift was, who you gave it to, why you chose this gift, and explain how they felt about it.', 'medium'),
(2, 'Object', 'Describe a piece of technology you find useful. You should say: what it is, when you got it, how you use it, and explain why you find it useful.', 'medium'),
(2, 'Object', 'Describe a piece of clothing that is special to you. You should say: what it is, when you got it, when you wear it, and explain why it is special.', 'easy'),
(2, 'Object', 'Describe a photo that you remember well. You should say: what is in the photo, when it was taken, who took it, and explain why you remember it.', 'medium'),

-- Experience (8)
(2, 'Experience', 'Describe a memorable event from your childhood. You should say: what the event was, when it happened, who was there, and explain why it was memorable.', 'medium'),
(2, 'Experience', 'Describe a time when you helped someone. You should say: who you helped, how you helped them, why you helped them, and explain how you felt about it.', 'medium'),
(2, 'Experience', 'Describe a difficult decision you had to make. You should say: what the decision was, when you had to make it, what you decided, and explain why it was difficult.', 'hard'),
(2, 'Experience', 'Describe a time you learned something new. You should say: what you learned, when you learned it, how you learned it, and explain how it was useful.', 'medium'),
(2, 'Experience', 'Describe a time you were pleasantly surprised. You should say: what happened, when it happened, who was involved, and explain why it was a pleasant surprise.', 'medium'),
(2, 'Experience', 'Describe an achievement you are proud of. You should say: what you achieved, when it happened, how difficult it was, and explain why you are proud.', 'medium'),
(2, 'Experience', 'Describe a mistake you learned from. You should say: what the mistake was, when it happened, what happened after, and explain what you learned.', 'hard'),
(2, 'Experience', 'Describe a time when you felt nervous. You should say: when it was, where you were, what caused the nervousness, and explain how you dealt with it.', 'medium'),

-- Activity (6)
(2, 'Activity', 'Describe a hobby or sport you enjoy. You should say: what it is, when you started it, why you enjoy it, and explain how it has changed your life.', 'medium'),
(2, 'Activity', 'Describe a skill you would like to learn. You should say: what the skill is, why you want to learn it, how you would learn it, and explain how it would benefit you.', 'medium'),
(2, 'Activity', 'Describe a project you worked on. You should say: what the project was, who you worked with, what you did, and explain what you learned from it.', 'hard'),
(2, 'Activity', 'Describe something you do to stay healthy. You should say: what it is, how often you do it, when you started, and explain how it helps you.', 'easy'),
(2, 'Activity', 'Describe a creative activity you enjoy. You should say: what it is, how you got into it, how often you do it, and explain why you find it creative.', 'medium'),
(2, 'Activity', 'Describe an outdoor activity you tried for the first time. You should say: what the activity was, where you did it, who you were with, and explain how you felt about it.', 'medium'),

-- Event (6)
(2, 'Event', 'Describe a festival or celebration you attended. You should say: what it was, where and when it took place, who you went with, and explain what you enjoyed about it.', 'medium'),
(2, 'Event', 'Describe a wedding you attended. You should say: whose wedding it was, where it was, what happened, and explain what was special about it.', 'medium'),
(2, 'Event', 'Describe a sporting event you watched. You should say: what it was, where you watched it, who was playing, and explain why you remember it.', 'medium'),
(2, 'Event', 'Describe a concert or live performance you attended. You should say: what it was, where and when it happened, who performed, and explain why you enjoyed it.', 'medium'),
(2, 'Event', 'Describe a family gathering you remember. You should say: when and where it was, who was there, what you did, and explain why you remember it.', 'easy'),
(2, 'Event', 'Describe a school event that was important to you. You should say: what the event was, when it happened, what you did, and explain why it was important.', 'medium'),

-- Media & Entertainment (6)
(2, 'Media & Entertainment', 'Describe a movie that left a strong impression on you. You should say: what the movie was about, when you saw it, who you watched it with, and explain why it impressed you.', 'medium'),
(2, 'Media & Entertainment', 'Describe a song that has a special meaning to you. You should say: what the song is, who performs it, when you first heard it, and explain why it is special.', 'medium'),
(2, 'Media & Entertainment', 'Describe a TV programme you enjoy watching. You should say: what it is about, how you discovered it, how often you watch it, and explain why you enjoy it.', 'easy'),
(2, 'Media & Entertainment', 'Describe a website you often visit. You should say: what the website is, how you found it, what you use it for, and explain why you visit it often.', 'easy'),
(2, 'Media & Entertainment', 'Describe a podcast or radio show you like. You should say: what it is about, how you started listening, how often you listen, and explain what you enjoy about it.', 'medium'),
(2, 'Media & Entertainment', 'Describe an article you read that was interesting. You should say: what it was about, where you read it, why you read it, and explain what you found interesting.', 'medium'),

-- Education & Work (6)
(2, 'Education & Work', 'Describe a subject you enjoyed studying at school. You should say: what the subject was, who taught it, what you learned, and explain why you enjoyed it.', 'easy'),
(2, 'Education & Work', 'Describe a job you would like to have in the future. You should say: what the job is, what qualifications you need, what the job involves, and explain why you want it.', 'medium'),
(2, 'Education & Work', 'Describe a useful lesson you learned outside of school. You should say: what the lesson was, when you learned it, who taught you, and explain how it has helped you.', 'hard'),
(2, 'Education & Work', 'Describe a time you had to work in a team. You should say: what the task was, who was in the team, what your role was, and explain how the teamwork went.', 'medium'),
(2, 'Education & Work', 'Describe a presentation you gave. You should say: what it was about, when and where you gave it, who the audience was, and explain how you felt.', 'medium'),
(2, 'Education & Work', 'Describe a course or training that improved your skills. You should say: what the course was, when you took it, what you learned, and explain how it helped you.', 'medium'),

-- Situation & Problem (6)
(2, 'Situation & Problem', 'Describe a problem you solved recently. You should say: what the problem was, when it happened, how you solved it, and explain how you felt afterwards.', 'medium'),
(2, 'Situation & Problem', 'Describe a time when you had to wait a long time. You should say: when it was, where you were, why you had to wait, and explain how you felt.', 'easy'),
(2, 'Situation & Problem', 'Describe a disagreement you had with someone. You should say: who you disagreed with, what it was about, how it was resolved, and explain what you learned from it.', 'hard'),
(2, 'Situation & Problem', 'Describe a time when you received good advice. You should say: who gave you the advice, what the advice was, when it was given, and explain how it helped you.', 'medium'),
(2, 'Situation & Problem', 'Describe a situation where you had to be polite. You should say: when it happened, who was involved, what you did, and explain why politeness was important.', 'medium'),
(2, 'Situation & Problem', 'Describe a time when you changed your mind about something. You should say: what you changed your mind about, when it happened, what made you change, and explain how you felt about it.', 'hard');


-- ============================================
-- PART 3: Two-way Discussion (4-5 minutes)
-- Abstract and analytical questions
-- ~120 questions across 15 categories
-- ============================================

INSERT INTO public.ielts_questions (part, category, question_text, difficulty) VALUES

-- Education (8)
(3, 'Education', 'How has education changed in your country over the last few decades?', 'hard'),
(3, 'Education', 'What do you think are the most important qualities of a good teacher?', 'medium'),
(3, 'Education', 'Should university education be free for everyone?', 'hard'),
(3, 'Education', 'How will technology change education in the future?', 'hard'),
(3, 'Education', 'Is practical experience more valuable than academic qualifications?', 'hard'),
(3, 'Education', 'What are the advantages and disadvantages of home schooling?', 'hard'),
(3, 'Education', 'Do you think exams are a good way to measure ability?', 'medium'),
(3, 'Education', 'Should schools focus more on life skills or academic subjects?', 'hard'),

-- Technology (8)
(3, 'Technology', 'How has technology changed the way people communicate?', 'medium'),
(3, 'Technology', 'What are the advantages and disadvantages of social media?', 'hard'),
(3, 'Technology', 'Will artificial intelligence replace human workers in the future?', 'hard'),
(3, 'Technology', 'How can we ensure that technology benefits everyone in society?', 'hard'),
(3, 'Technology', 'Should children be limited in how much time they spend on screens?', 'medium'),
(3, 'Technology', 'How has online shopping changed the retail industry?', 'medium'),
(3, 'Technology', 'Do you think technology makes people more or less creative?', 'hard'),
(3, 'Technology', 'What role should governments play in regulating technology companies?', 'hard'),

-- Environment (8)
(3, 'Environment', 'What are the main environmental problems facing your country?', 'medium'),
(3, 'Environment', 'What can individuals do to protect the environment?', 'medium'),
(3, 'Environment', 'Should governments force companies to be more environmentally friendly?', 'hard'),
(3, 'Environment', 'How can we balance economic development with environmental protection?', 'hard'),
(3, 'Environment', 'Do you think climate change can be reversed?', 'hard'),
(3, 'Environment', 'Should developed countries help developing countries with environment issues?', 'hard'),
(3, 'Environment', 'Why do some people not care about the environment?', 'medium'),
(3, 'Environment', 'How can cities become more sustainable?', 'hard'),

-- Society (8)
(3, 'Society', 'How has family life changed in modern society?', 'hard'),
(3, 'Society', 'What are the advantages and disadvantages of living in a city?', 'medium'),
(3, 'Society', 'How can society better support elderly people?', 'hard'),
(3, 'Society', 'Is work-life balance possible in modern society?', 'hard'),
(3, 'Society', 'Do you think the gap between rich and poor is growing?', 'hard'),
(3, 'Society', 'What are the main causes of crime in society?', 'hard'),
(3, 'Society', 'Should everyone do volunteer work?', 'medium'),
(3, 'Society', 'How has the role of women in society changed?', 'hard'),

-- Culture (8)
(3, 'Culture', 'How important is it to preserve traditional culture?', 'hard'),
(3, 'Culture', 'Has globalization had a positive or negative effect on culture?', 'hard'),
(3, 'Culture', 'Should museums and art galleries be free?', 'medium'),
(3, 'Culture', 'How will culture change in the next 50 years?', 'hard'),
(3, 'Culture', 'Why is it important to learn about other cultures?', 'medium'),
(3, 'Culture', 'Do you think younger generations value traditions less?', 'medium'),
(3, 'Culture', 'How does food reflect a country''s culture?', 'medium'),
(3, 'Culture', 'Should governments invest more in the arts?', 'hard'),

-- Health (8)
(3, 'Health', 'What can governments do to improve public health?', 'hard'),
(3, 'Health', 'Is modern life more or less stressful than in the past?', 'medium'),
(3, 'Health', 'Should healthcare be free for all citizens?', 'hard'),
(3, 'Health', 'How important is mental health compared to physical health?', 'hard'),
(3, 'Health', 'Why do many people find it difficult to exercise regularly?', 'medium'),
(3, 'Health', 'Should unhealthy food be taxed more heavily?', 'hard'),
(3, 'Health', 'How has the internet affected people''s mental health?', 'hard'),
(3, 'Health', 'What can schools do to promote healthier lifestyles among students?', 'medium'),

-- Work (8)
(3, 'Work', 'How has the nature of work changed in recent years?', 'medium'),
(3, 'Work', 'What makes a job satisfying?', 'medium'),
(3, 'Work', 'Will remote work become the norm in the future?', 'hard'),
(3, 'Work', 'Is it better to work for a large company or start your own business?', 'hard'),
(3, 'Work', 'Should people be paid the same for similar work regardless of location?', 'hard'),
(3, 'Work', 'How important is job security compared to job satisfaction?', 'medium'),
(3, 'Work', 'Do you think people will work fewer hours in the future?', 'hard'),
(3, 'Work', 'What skills will be most important in the future job market?', 'hard'),

-- Media (8)
(3, 'Media', 'How has the internet changed journalism?', 'hard'),
(3, 'Media', 'Do celebrities have too much influence on young people?', 'medium'),
(3, 'Media', 'Should there be stricter control of what appears on the internet?', 'hard'),
(3, 'Media', 'Will traditional newspapers disappear completely?', 'medium'),
(3, 'Media', 'How can people tell the difference between real and fake news?', 'hard'),
(3, 'Media', 'Should advertising be more regulated?', 'medium'),
(3, 'Media', 'Do you think the media has too much power?', 'hard'),
(3, 'Media', 'How has social media changed the way news is reported?', 'hard'),

-- Travel & Tourism (8)
(3, 'Travel & Tourism', 'What are the benefits of international tourism?', 'medium'),
(3, 'Travel & Tourism', 'Can tourism damage local environments and cultures?', 'hard'),
(3, 'Travel & Tourism', 'How has international travel changed over the last 20 years?', 'medium'),
(3, 'Travel & Tourism', 'Should people reduce air travel to help the environment?', 'hard'),
(3, 'Travel & Tourism', 'What makes a destination attractive to tourists?', 'medium'),
(3, 'Travel & Tourism', 'Is it better to travel independently or with a guided tour?', 'medium'),
(3, 'Travel & Tourism', 'How does tourism benefit local economies?', 'medium'),
(3, 'Travel & Tourism', 'Do you think space tourism will become popular in the future?', 'hard'),

-- Language & Communication (8)
(3, 'Language & Communication', 'Is it important for everyone to learn English?', 'medium'),
(3, 'Language & Communication', 'Should minority languages be protected?', 'hard'),
(3, 'Language & Communication', 'How has technology changed the way we communicate?', 'medium'),
(3, 'Language & Communication', 'Is face-to-face communication better than online communication?', 'medium'),
(3, 'Language & Communication', 'Do you think translation technology will replace language learning?', 'hard'),
(3, 'Language & Communication', 'How does language influence the way people think?', 'hard'),
(3, 'Language & Communication', 'Should schools teach more foreign languages?', 'medium'),
(3, 'Language & Communication', 'Is body language important in communication?', 'medium'),

-- Relationships & Community (8)
(3, 'Relationships & Community', 'How have relationships between neighbours changed?', 'medium'),
(3, 'Relationships & Community', 'Is community spirit declining in modern cities?', 'hard'),
(3, 'Relationships & Community', 'What are the most important values in a friendship?', 'medium'),
(3, 'Relationships & Community', 'How can communities become more inclusive?', 'hard'),
(3, 'Relationships & Community', 'Do you think online friendships are as valuable as real-life ones?', 'hard'),
(3, 'Relationships & Community', 'How important is it for families to eat together?', 'medium'),
(3, 'Relationships & Community', 'Should people be more involved in their local communities?', 'medium'),
(3, 'Relationships & Community', 'Has social media made people more or less connected?', 'hard'),

-- Money & Economy (8)
(3, 'Money & Economy', 'Is money the most important factor in choosing a job?', 'medium'),
(3, 'Money & Economy', 'Should governments provide a basic income for all citizens?', 'hard'),
(3, 'Money & Economy', 'How important is financial education for young people?', 'medium'),
(3, 'Money & Economy', 'Do you think consumerism is a problem in modern society?', 'hard'),
(3, 'Money & Economy', 'Should there be a maximum wage as well as a minimum wage?', 'hard'),
(3, 'Money & Economy', 'How has the sharing economy changed the way we live?', 'hard'),
(3, 'Money & Economy', 'Is it better to save money or spend it?', 'medium'),
(3, 'Money & Economy', 'What effect does advertising have on people''s spending habits?', 'medium'),

-- Youth & Aging (8)
(3, 'Youth & Aging', 'What challenges do young people face today?', 'medium'),
(3, 'Youth & Aging', 'Should the retirement age be raised?', 'hard'),
(3, 'Youth & Aging', 'How can young people and old people learn from each other?', 'medium'),
(3, 'Youth & Aging', 'Do young people today have more opportunities than previous generations?', 'hard'),
(3, 'Youth & Aging', 'How should society prepare for an aging population?', 'hard'),
(3, 'Youth & Aging', 'Are young people today more informed or less informed than in the past?', 'hard'),
(3, 'Youth & Aging', 'Should elderly people continue working if they want to?', 'medium'),
(3, 'Youth & Aging', 'What responsibilities do young people have towards older generations?', 'hard'),

-- Science & Innovation (8)
(3, 'Science & Innovation', 'How important is scientific research for a country''s development?', 'hard'),
(3, 'Science & Innovation', 'Should governments spend more money on space exploration?', 'hard'),
(3, 'Science & Innovation', 'What are the ethical concerns about genetic engineering?', 'hard'),
(3, 'Science & Innovation', 'How can science and technology help solve world problems?', 'hard'),
(3, 'Science & Innovation', 'Do you think people trust science more or less than they used to?', 'medium'),
(3, 'Science & Innovation', 'Should there be limits on scientific research?', 'hard'),
(3, 'Science & Innovation', 'How can we encourage more young people to study science?', 'medium'),
(3, 'Science & Innovation', 'What inventions do you think will be most important in the next 20 years?', 'hard'),

-- Law & Justice (8)
(3, 'Law & Justice', 'What is the purpose of punishment in the justice system?', 'hard'),
(3, 'Law & Justice', 'Should the legal system focus more on rehabilitation than punishment?', 'hard'),
(3, 'Law & Justice', 'Are laws always fair?', 'hard'),
(3, 'Law & Justice', 'How can we reduce crime in society?', 'medium'),
(3, 'Law & Justice', 'Should young offenders be treated differently from adult criminals?', 'hard'),
(3, 'Law & Justice', 'Do you think surveillance cameras help reduce crime?', 'medium'),
(3, 'Law & Justice', 'How important is it in a democracy for people to know their rights?', 'hard'),
(3, 'Law & Justice', 'Should people who commit minor offences be sent to prison?', 'hard');


-- ============================================================
-- apps/lexica/supabase/migration_study_buddy.sql
-- ============================================================

-- ============================================
-- Study Buddy System
-- Chạy trong Supabase SQL Editor
-- ============================================

-- Profiles (linked to Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nickname TEXT NOT NULL DEFAULT 'Anonymous',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily activity snapshot (upserted each session)
CREATE TABLE IF NOT EXISTS public.daily_activity (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    words_swiped INT NOT NULL DEFAULT 0,
    words_learned_today INT NOT NULL DEFAULT 0,
    daily_goal INT NOT NULL DEFAULT 10,
    goal_met BOOLEAN NOT NULL DEFAULT FALSE,
    streak INT NOT NULL DEFAULT 0,
    UNIQUE(user_id, date)
);

-- Buddy pairs
CREATE TABLE IF NOT EXISTS public.buddy_pairs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_a_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user_b_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    duo_streak INT NOT NULL DEFAULT 0,
    last_duo_date DATE,
    target_words INT NOT NULL DEFAULT 10,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_a_id, user_b_id),
    CHECK(user_a_id != user_b_id)
);

-- Buddy invites (6-char code, expires 48h)
CREATE TABLE IF NOT EXISTS public.buddy_invites (
    code TEXT PRIMARY KEY,
    from_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '48 hours',
    accepted BOOLEAN NOT NULL DEFAULT FALSE
);

-- ============================================
-- RLS Policies
-- ============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buddy_pairs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buddy_invites ENABLE ROW LEVEL SECURITY;

-- Profiles: own row + buddies can read yours
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
CREATE POLICY "Users can read own profile"
    ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
    ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Buddies can read each other's profiles
DROP POLICY IF EXISTS "Buddies can read each other profiles" ON public.profiles;
CREATE POLICY "Buddies can read each other profiles"
    ON public.profiles FOR SELECT
    USING (
        id = auth.uid() OR
        EXISTS (
            SELECT 1 FROM public.buddy_pairs
            WHERE (user_a_id = auth.uid() AND user_b_id = id)
               OR (user_b_id = auth.uid() AND user_a_id = id)
        )
    );

-- Daily activity: own rows + buddies can read
DROP POLICY IF EXISTS "Users manage own activity" ON public.daily_activity;
CREATE POLICY "Users manage own activity"
    ON public.daily_activity FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Buddies can read each other activity" ON public.daily_activity;
CREATE POLICY "Buddies can read each other activity"
    ON public.daily_activity FOR SELECT
    USING (
        user_id = auth.uid() OR
        EXISTS (
            SELECT 1 FROM public.buddy_pairs
            WHERE (user_a_id = auth.uid() AND user_b_id = user_id)
               OR (user_b_id = auth.uid() AND user_a_id = user_id)
        )
    );

-- Buddy pairs: members can read, anyone can insert (for acceptance)
DROP POLICY IF EXISTS "Buddy members can read pairs" ON public.buddy_pairs;
CREATE POLICY "Buddy members can read pairs"
    ON public.buddy_pairs FOR SELECT
    USING (user_a_id = auth.uid() OR user_b_id = auth.uid());

DROP POLICY IF EXISTS "Anyone authenticated can insert pair" ON public.buddy_pairs;
CREATE POLICY "Anyone authenticated can insert pair"
    ON public.buddy_pairs FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Members can update duo streak" ON public.buddy_pairs;
CREATE POLICY "Members can update duo streak"
    ON public.buddy_pairs FOR UPDATE
    USING (user_a_id = auth.uid() OR user_b_id = auth.uid());

-- Buddy invites: owner manages, anyone authenticated can read to accept
DROP POLICY IF EXISTS "Owner manages invite" ON public.buddy_invites;
CREATE POLICY "Owner manages invite"
    ON public.buddy_invites FOR ALL USING (from_user_id = auth.uid());

DROP POLICY IF EXISTS "Anyone authenticated can read invite" ON public.buddy_invites;
CREATE POLICY "Anyone authenticated can read invite"
    ON public.buddy_invites FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Anyone authenticated can accept invite" ON public.buddy_invites;
CREATE POLICY "Anyone authenticated can accept invite"
    ON public.buddy_invites FOR UPDATE USING (auth.uid() IS NOT NULL);


-- ============================================================
-- apps/lexica/supabase/migration_study_buddy_fix.sql
-- ============================================================

-- ============================================
-- Fix: Grant permissions + missing DELETE policy
-- Chạy trong Supabase SQL Editor sau migration_study_buddy.sql
-- ============================================

-- 1. Grant table-level access cho role authenticated
--    (Tables tạo qua SQL Editor không tự cấp quyền này)
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles         TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_activity   TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_pairs      TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_invites    TO authenticated;

-- 2. Thêm DELETE policy cho buddy_pairs (bị thiếu trong migration đầu)
DROP POLICY IF EXISTS "Members can delete own pair" ON public.buddy_pairs;
CREATE POLICY "Members can delete own pair"
    ON public.buddy_pairs FOR DELETE
    USING (user_a_id = auth.uid() OR user_b_id = auth.uid());

-- 3. Bỏ policy SELECT trùng lặp trên profiles
--    ("Buddies can read each other profiles" đã bao gồm trường hợp đọc profile bản thân)
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;


-- ============================================================
-- apps/lexica/supabase/migration_study_buddy_fix2.sql
-- ============================================================

-- ============================================
-- Fix 2: Tạo lại các bảng bị thiếu
-- (migration_study_buddy.sql dùng uuid_generate_v4() không có sẵn
--  trong Supabase project mới → daily_activity, buddy_pairs,
--  buddy_invites chưa được tạo → RLS policy trên profiles crash)
--
-- Chạy toàn bộ file này trong Supabase SQL Editor
-- ============================================

-- Tạo daily_activity (dùng gen_random_uuid() thay uuid_generate_v4)
CREATE TABLE IF NOT EXISTS public.daily_activity (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    words_swiped INT NOT NULL DEFAULT 0,
    words_learned_today INT NOT NULL DEFAULT 0,
    daily_goal INT NOT NULL DEFAULT 10,
    goal_met BOOLEAN NOT NULL DEFAULT FALSE,
    streak INT NOT NULL DEFAULT 0,
    UNIQUE(user_id, date)
);

-- Tạo buddy_pairs
CREATE TABLE IF NOT EXISTS public.buddy_pairs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_a_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user_b_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    duo_streak INT NOT NULL DEFAULT 0,
    last_duo_date DATE,
    target_words INT NOT NULL DEFAULT 10,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_a_id, user_b_id),
    CHECK(user_a_id != user_b_id)
);

-- Tạo buddy_invites
CREATE TABLE IF NOT EXISTS public.buddy_invites (
    code TEXT PRIMARY KEY,
    from_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '48 hours',
    accepted BOOLEAN NOT NULL DEFAULT FALSE
);

-- ── RLS ─────────────────────────────────────────────────

ALTER TABLE public.daily_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buddy_pairs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buddy_invites  ENABLE ROW LEVEL SECURITY;

-- daily_activity
DROP POLICY IF EXISTS "Users manage own activity"           ON public.daily_activity;
DROP POLICY IF EXISTS "Buddies can read each other activity" ON public.daily_activity;

DROP POLICY IF EXISTS "Users manage own activity" ON public.daily_activity;
CREATE POLICY "Users manage own activity"
    ON public.daily_activity FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Buddies can read each other activity"
    ON public.daily_activity FOR SELECT
    USING (
        user_id = auth.uid() OR
        EXISTS (
            SELECT 1 FROM public.buddy_pairs
            WHERE (user_a_id = auth.uid() AND user_b_id = user_id)
               OR (user_b_id = auth.uid() AND user_a_id = user_id)
        )
    );

-- buddy_pairs
DROP POLICY IF EXISTS "Buddy members can read pairs"       ON public.buddy_pairs;
DROP POLICY IF EXISTS "Anyone authenticated can insert pair" ON public.buddy_pairs;
DROP POLICY IF EXISTS "Members can update duo streak"      ON public.buddy_pairs;
DROP POLICY IF EXISTS "Members can delete own pair"        ON public.buddy_pairs;

DROP POLICY IF EXISTS "Buddy members can read pairs" ON public.buddy_pairs;
CREATE POLICY "Buddy members can read pairs"
    ON public.buddy_pairs FOR SELECT
    USING (user_a_id = auth.uid() OR user_b_id = auth.uid());

DROP POLICY IF EXISTS "Anyone authenticated can insert pair" ON public.buddy_pairs;
CREATE POLICY "Anyone authenticated can insert pair"
    ON public.buddy_pairs FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Members can update duo streak" ON public.buddy_pairs;
CREATE POLICY "Members can update duo streak"
    ON public.buddy_pairs FOR UPDATE
    USING (user_a_id = auth.uid() OR user_b_id = auth.uid());

DROP POLICY IF EXISTS "Members can delete own pair" ON public.buddy_pairs;
CREATE POLICY "Members can delete own pair"
    ON public.buddy_pairs FOR DELETE
    USING (user_a_id = auth.uid() OR user_b_id = auth.uid());

-- buddy_invites
DROP POLICY IF EXISTS "Owner manages invite"                ON public.buddy_invites;
DROP POLICY IF EXISTS "Anyone authenticated can read invite" ON public.buddy_invites;
DROP POLICY IF EXISTS "Anyone authenticated can accept invite" ON public.buddy_invites;

DROP POLICY IF EXISTS "Owner manages invite" ON public.buddy_invites;
CREATE POLICY "Owner manages invite"
    ON public.buddy_invites FOR ALL USING (from_user_id = auth.uid());

CREATE POLICY "Anyone authenticated can read invite"
    ON public.buddy_invites FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Anyone authenticated can accept invite" ON public.buddy_invites;
CREATE POLICY "Anyone authenticated can accept invite"
    ON public.buddy_invites FOR UPDATE USING (auth.uid() IS NOT NULL);

-- ── Grants ───────────────────────────────────────────────

GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles       TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_activity TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_pairs    TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_invites  TO authenticated;


-- ============================================================
-- apps/lexica/supabase/migration_study_buddy_fix3.sql
-- ============================================================

-- ============================================
-- Fix 3: Đơn giản hoá RLS policies trên profiles
-- (cross-table reference tới buddy_pairs gây PostgREST cache lỗi)
--
-- Chạy file này trong Supabase SQL Editor
-- ============================================

-- Bỏ hết SELECT policies cũ trên profiles
DROP POLICY IF EXISTS "Users can read own profile"           ON public.profiles;
DROP POLICY IF EXISTS "Buddies can read each other profiles" ON public.profiles;

-- Policy mới: mọi user đã xác thực đều đọc được nickname của nhau
-- (nickname không phải dữ liệu nhạy cảm)
DROP POLICY IF EXISTS "Authenticated users can read profiles" ON public.profiles;
CREATE POLICY "Authenticated users can read profiles"
    ON public.profiles FOR SELECT
    USING (auth.uid() IS NOT NULL);

-- Đảm bảo grants vẫn còn
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles       TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_activity TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_pairs    TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_invites  TO authenticated;


-- ============================================================
-- apps/lexica/supabase/migration_study_buddy_fix4.sql
-- ============================================================

-- ============================================
-- Fix 4: Idempotent — chạy bao nhiêu lần cũng OK
-- ============================================

-- First ensure the profiles table has the nickname column
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS nickname TEXT NOT NULL DEFAULT 'Anonymous';

-- profiles policies
DROP POLICY IF EXISTS "profiles_select" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update" ON public.profiles;
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
DROP POLICY IF EXISTS "Buddies can read each other profiles" ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can read profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;

DROP POLICY IF EXISTS "profiles_select" ON public.profiles;
CREATE POLICY "profiles_select"
    ON public.profiles FOR SELECT
    USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "profiles_insert" ON public.profiles;
CREATE POLICY "profiles_insert"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update" ON public.profiles;
CREATE POLICY "profiles_update"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id AND length(nickname) BETWEEN 1 AND 20);

-- Grants (lặp lại cho chắc)
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_activity TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_pairs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.buddy_invites TO authenticated;

-- Force PostgREST reload schema cache
NOTIFY pgrst, 'reload schema';


-- ============================================================
-- apps/lexica/supabase/migration_game_challenges.sql
-- ============================================================

-- ============================================
-- Lexica Game Challenges
-- Chạy trong Supabase SQL Editor
-- ============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.game_challenges (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_type TEXT NOT NULL CHECK (game_type IN ('speed', 'type', 'truefalse', 'scramble', 'combo')),
    score INTEGER NOT NULL CHECK (score >= 0),
    nickname TEXT NOT NULL DEFAULT 'Anonymous',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Public read/insert (no auth needed for anonymous challenges)
ALTER TABLE public.game_challenges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read challenges" ON public.game_challenges;
CREATE POLICY "Anyone can read challenges"
    ON public.game_challenges FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Anyone can create challenges" ON public.game_challenges;
CREATE POLICY "Anyone can create challenges"
    ON public.game_challenges FOR INSERT
    WITH CHECK (true);

-- Auto-delete challenges older than 7 days (keep DB clean)
-- Run as a Supabase scheduled function or pg_cron if needed
-- DELETE FROM public.game_challenges WHERE created_at < NOW() - INTERVAL '7 days';


-- ============================================================
-- apps/lexica/supabase/migration_add_response.sql
-- ============================================================

-- ============================================
-- Thêm cột response cho game_challenges
-- Chạy trong Supabase SQL Editor sau migration đầu tiên
-- ============================================

ALTER TABLE public.game_challenges
    ADD COLUMN IF NOT EXISTS response_score INTEGER,
    ADD COLUMN IF NOT EXISTS response_nickname TEXT;

-- Cho phép update để lưu kết quả của người được thách đấu
DROP POLICY IF EXISTS "Anyone can update response" ON public.game_challenges;
CREATE POLICY "Anyone can update response"
    ON public.game_challenges FOR UPDATE
    USING (true)
    WITH CHECK (true);


-- ============================================================
-- apps/cortex-core-api/supabase/migration_phase1_core.sql
-- ============================================================

-- Cortex Core API tables (action_logs, app_backups, user_vocabulary,
-- linguistic_profiles).
-- Idempotent: safe to run on a project that already has some of these.

create extension if not exists "uuid-ossp";

-- Append-only activity log from every app (POST /actions/log)
create table if not exists action_logs (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null,
  app_source text not null,
  action_type text not null,
  metadata jsonb,
  timestamp timestamptz default now()
);

create index if not exists action_logs_user_time_idx
  on action_logs (user_id, timestamp desc);

-- Raw state snapshot per user + app (POST /v1/sync/backup)
create table if not exists app_backups (
  user_id uuid not null,
  app_source text not null,
  raw_data jsonb not null,
  updated_at timestamptz default now(),
  primary key (user_id, app_source)
);

-- Words a user has learned, one row per user + word (POST /actions/log
-- with appSource=lexica). Unique key matches upsert onConflict 'user_id,word'.
create table if not exists user_vocabulary (
  user_id uuid not null,
  word text not null,
  created_at timestamptz default now(),
  primary key (user_id, word)
);

-- Aggregated per-user linguistic stats, upserted by ActionsController and
-- read live by the landing dashboard. Upsert onConflict is 'user_id'.
-- Column set must cover every field the API writes: it spreads the existing
-- row into each update.
create table if not exists linguistic_profiles (
  user_id uuid primary key,
  vocabulary_size integer default 0,
  active_vocab_count integer default 0,
  passive_vocab_count integer default 0,
  passive_vocab_samples text[] default '{}',
  top_topics text[] default '{}',
  fluency_score double precision,
  difficulty_recommendation jsonb,
  refined_insights jsonb default '{}'::jsonb,
  last_updated timestamptz default now()
);

-- Landing dashboard subscribes to postgres_changes on linguistic_profiles
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and tablename = 'linguistic_profiles'
     ) then
    alter publication supabase_realtime add table public.linguistic_profiles;
  end if;
end $$;

