#!/usr/bin/env python3
"""Generates supabase/seed_studio_lexemes.sql from Lexica's core cards.

Run from the repo root after changing apps/lexica/app/data/vocabCards.ts:
  python3 apps/cortex-core-api/scripts/build-studio-lexemes.py
"""
import re
from pathlib import Path

SRC = Path('apps/lexica/app/data/vocabCards.ts')
OUT = Path('apps/cortex-core-api/supabase/seed_studio_lexemes.sql')

card_re = re.compile(
    r'"id":\s*"(?P<id>v\d+)",\s*"word":\s*"(?P<word>[^"]+)",'
    r'(?:\s*"ipa":\s*"(?P<ipa>[^"]*)",)?\s*"elo":\s*(?P<elo>\d+),\s*"level":\s*"(?P<level>\w+)"'
)

def q(s):
    return "null" if s is None else "'" + s.replace("'", "''") + "'"

rows = {}
for m in card_re.finditer(SRC.read_text(encoding='utf-8')):
    word = m['word'].strip().lower()
    rows.setdefault(word, (m['ipa'], int(m['elo']), m['level']))

lines = [
    '-- GENERATED by apps/cortex-core-api/scripts/build-studio-lexemes.py — do not edit by hand.',
    f'-- {len(rows)} words from Lexica core cards; the Studio generator may only teach these',
    '-- (plus words editors add in Studio).',
    'insert into studio_lexemes (word, ipa, elo, level, in_core) values',
]
values = [f'  ({q(w)}, {q(ipa)}, {elo}, {q(level)}, true)' for w, (ipa, elo, level) in sorted(rows.items())]
lines.append(',\n'.join(values))
lines.append('on conflict (word) do nothing;')
OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Wrote {OUT} ({len(rows)} words)')
